spring:
  application:
    name: socks-invent
  datasource:
    url: jdbc:postgresql://localhost:8081/socks
    username: admin
    password: admin
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql: true
logging:
  level:
    root: INFO
    socks.socks_invent: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/socks-warehouse.log
    max-size: 10MB
    max-history: 7